# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: zhaoqing-wang
          template: classic
          base: header, repositories, metadata
          base_skip: yes
          config_timezone: Asia/Shanghai
          config_twemoji: yes
          extras_css: |
            /* Override green contribution colors to grayscale */
            rect[fill="#ebedf0"], path[fill="#ebedf0"] { fill: #eaeaea !important; }
            rect[fill="#9be9a8"], path[fill="#9be9a8"] { fill: #c6c6c6 !important; }
            rect[fill="#40c463"], path[fill="#40c463"] { fill: #959595 !important; }
            rect[fill="#30a14e"], path[fill="#30a14e"] { fill: #636363 !important; }
            rect[fill="#216e39"], path[fill="#216e39"] { fill: #333333 !important; }
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%